### ISSUE TITLE
vs报错：cout不属于std

### ISSUE THREAD

**Issue by 1250449439** [SabreHawk-Studio/Reports-And-Issues#33]
![default](https://user-images.githubusercontent.com/44594408/50423479-d6965500-0890-11e9-8500-2750d250471b.PNG)
https://github.com/1250449439/aaa/tree/master/ConsoleApplication2

**Comment by SabreHawk** [comment]
*这里的问题不在于 cout 的命名空间不属于，而是使用命名空间的位置错误：*
正确的写法应该是 using namespace std;紧跟在头文件声明后面：
>> #include <iostream>
>> #include ...
>> using namespace std;
>>
>> int main(){
>> ...
>>}

这边还要注意的一点是在第10行using的前面不需要加大括号，删除的时候记得把这一对大括号删掉:)

**Comment by assassin945** [comment]
这里还有一个问题，"#include "stdafx.h""  这条语句必须始终保持在最顶端

**Comment by SabreHawk** [comment]
stdafx.h这个文件是在用VS创建工程的时候自动生成的（别的IDE是没有的），主要用来包括一些头文件。你可以打开这个文件，看看里面使用了那些头文件。如果不需要这个文件的话，把他删掉也可以。
PS：下次用Markdown代码框的形式贴代码，截图的话，其他人不能复制你的代码直接跑。

**Comment by 1250449439** [comment]
问题解决了，开心开心，谢谢你们的帮助

**Comment by SabreHawk** [comment]
没事~加油！
